//! Forward Error Correction (FEC) and video packet framing.
//!
//! This module defines the wire format for RustDesk's UDP video transport
//! and provides fragmentation/reassembly of video frames into MTU-sized
//! packets with FEC headers.
//!
//! # Wire Format
//!
//! Each UDP datagram carries a 24-byte [`VideoPacketHeader`] followed by
//! payload bytes. The header is serialized in little-endian byte order
//! using `#[repr(C, packed)]` for zero-copy compatibility.
//!
//! ```text
//! +------------------+---------------------------+
//! | VideoPacketHeader |       Payload             |
//! |    (24 bytes)     |   (up to ~1376 bytes)     |
//! +------------------+---------------------------+
//! ```
//!
//! # FEC Strategy
//!
//! XOR-based forward error correction: for every N data packets in a group,
//! one parity packet is generated by XOR-ing all data payloads together
//! (shorter payloads are zero-padded to the length of the longest).
//!
//! This allows recovery of any single lost data packet per FEC group.
//! If 2 or more data packets are lost, recovery is not possible.
//!
//! # Frame Fragmentation
//!
//! Encoded video frames (H.264/H.265 NALUs) are split into fragments that
//! fit within the transport's MTU. Each fragment gets its own header with
//! `fragment_index` and `fragment_count` fields for reassembly.

use std::collections::HashMap;

/// Maximum payload bytes per packet. Assumes ~1400 byte MTU minus the
/// 24-byte header.
pub const MAX_PAYLOAD_SIZE: usize = 1376;

/// Size of the [`VideoPacketHeader`] in bytes. Verified by compile-time
/// and runtime tests.
pub const HEADER_SIZE: usize = 24;

/// Frame type: predictive frame (depends on previous frames).
pub const FRAME_TYPE_P: u8 = 0;

/// Frame type: intra/key frame (self-contained, no dependencies).
pub const FRAME_TYPE_I: u8 = 1;

/// Frame type: FEC parity packet (XOR of all data packets in the group).
pub const FRAME_TYPE_PARITY: u8 = 2;

/// Video packet header for the UDP transport.
///
/// This 24-byte header prefixes every video datagram. It carries enough
/// metadata for the receiver to:
/// - Detect packet loss (via `sequence` gaps)
/// - Reassemble fragmented frames (`fragment_index`, `fragment_count`)
/// - Apply FEC recovery (`fec_group_id`, `fec_data_count`, `fec_parity_count`)
/// - Calculate jitter (`timestamp_ms`)
/// - Prioritize keyframes (`frame_type`)
///
/// # Wire Layout
///
/// All fields are little-endian. The struct uses `#[repr(C, packed)]` to
/// guarantee the layout matches the wire format exactly.
///
/// | Offset | Size | Field             |
/// |--------|------|-------------------|
/// | 0      | 4    | sequence          |
/// | 4      | 4    | frame_number      |
/// | 8      | 2    | fragment_index    |
/// | 10     | 2    | fragment_count    |
/// | 12     | 1    | frame_type        |
/// | 13     | 1    | fec_group_id      |
/// | 14     | 1    | fec_data_count    |
/// | 15     | 1    | fec_parity_count  |
/// | 16     | 4    | timestamp_ms      |
/// | 20     | 4    | payload_length    |
// Note: `#[repr(C)]` (not `packed`) is used because the field order is
// already naturally aligned — no padding is inserted, and the struct is
// exactly 24 bytes. This avoids undefined behavior from creating references
// to unaligned fields while maintaining wire-format compatibility.
// The `header_size_is_24_bytes` test verifies this at compile time.
#[repr(C)]
#[derive(Debug, Clone, Copy)]
pub struct VideoPacketHeader {
    /// Per-packet monotonic sequence number. Wraps at `u32::MAX`.
    /// Used by the receiver to detect gaps (packet loss).
    pub sequence: u32,

    /// Per-frame monotonic counter. All fragments of the same frame share
    /// the same `frame_number`.
    pub frame_number: u32,

    /// Zero-based index of this fragment within the frame.
    /// Range: `0..fragment_count`.
    pub fragment_index: u16,

    /// Total number of data fragments in this frame (excludes FEC parity
    /// packets).
    pub fragment_count: u16,

    /// Frame type: [`FRAME_TYPE_P`] (0) or [`FRAME_TYPE_I`] (1).
    pub frame_type: u8,

    /// Identifies which FEC group this packet belongs to. All data and
    /// parity packets in the same group share this ID.
    pub fec_group_id: u8,

    /// Number of data packets in this FEC group.
    pub fec_data_count: u8,

    /// Number of parity packets in this FEC group.
    pub fec_parity_count: u8,

    /// Sender timestamp in milliseconds since an arbitrary epoch.
    /// Used for jitter estimation and one-way delay calculation.
    pub timestamp_ms: u32,

    /// Number of payload bytes following this header.
    pub payload_length: u32,
}

impl VideoPacketHeader {
    /// Serialize this header to a 24-byte little-endian byte array.
    pub fn to_bytes(&self) -> [u8; HEADER_SIZE] {
        let mut buf = [0u8; HEADER_SIZE];
        buf[0..4].copy_from_slice(&self.sequence.to_le_bytes());
        buf[4..8].copy_from_slice(&self.frame_number.to_le_bytes());
        buf[8..10].copy_from_slice(&self.fragment_index.to_le_bytes());
        buf[10..12].copy_from_slice(&self.fragment_count.to_le_bytes());
        buf[12] = self.frame_type;
        buf[13] = self.fec_group_id;
        buf[14] = self.fec_data_count;
        buf[15] = self.fec_parity_count;
        buf[16..20].copy_from_slice(&self.timestamp_ms.to_le_bytes());
        buf[20..24].copy_from_slice(&self.payload_length.to_le_bytes());
        buf
    }

    /// Deserialize a header from a 24-byte little-endian byte slice.
    ///
    /// # Errors
    ///
    /// Returns `None` if `data` is shorter than [`HEADER_SIZE`] bytes.
    pub fn from_bytes(data: &[u8]) -> Option<Self> {
        if data.len() < HEADER_SIZE {
            return None;
        }
        Some(Self {
            sequence: u32::from_le_bytes([data[0], data[1], data[2], data[3]]),
            frame_number: u32::from_le_bytes([data[4], data[5], data[6], data[7]]),
            fragment_index: u16::from_le_bytes([data[8], data[9]]),
            fragment_count: u16::from_le_bytes([data[10], data[11]]),
            frame_type: data[12],
            fec_group_id: data[13],
            fec_data_count: data[14],
            fec_parity_count: data[15],
            timestamp_ms: u32::from_le_bytes([data[16], data[17], data[18], data[19]]),
            payload_length: u32::from_le_bytes([data[20], data[21], data[22], data[23]]),
        })
    }
}

impl PartialEq for VideoPacketHeader {
    fn eq(&self, other: &Self) -> bool {
        self.sequence == other.sequence
            && self.frame_number == other.frame_number
            && self.fragment_index == other.fragment_index
            && self.fragment_count == other.fragment_count
            && self.frame_type == other.frame_type
            && self.fec_group_id == other.fec_group_id
            && self.fec_data_count == other.fec_data_count
            && self.fec_parity_count == other.fec_parity_count
            && self.timestamp_ms == other.timestamp_ms
            && self.payload_length == other.payload_length
    }
}

impl Eq for VideoPacketHeader {}

/// A complete packet: header + payload, ready to send as a single datagram.
#[derive(Debug, Clone)]
pub struct VideoPacket {
    pub header: VideoPacketHeader,
    pub payload: Vec<u8>,
}

impl VideoPacket {
    /// Serialize this packet (header + payload) into a byte vector suitable
    /// for sending as a single UDP datagram.
    pub fn to_bytes(&self) -> Vec<u8> {
        let mut buf = Vec::with_capacity(HEADER_SIZE + self.payload.len());
        buf.extend_from_slice(&self.header.to_bytes());
        buf.extend_from_slice(&self.payload);
        buf
    }

    /// Deserialize a packet from raw datagram bytes.
    ///
    /// Returns `None` if the data is too short for a header or if
    /// `payload_length` exceeds the available data.
    pub fn from_bytes(data: &[u8]) -> Option<Self> {
        let header = VideoPacketHeader::from_bytes(data)?;
        let payload_len = header.payload_length as usize;
        if data.len() < HEADER_SIZE + payload_len {
            return None;
        }
        let payload = data[HEADER_SIZE..HEADER_SIZE + payload_len].to_vec();
        Some(Self { header, payload })
    }
}

/// Result of fragmenting a video frame.
pub struct FragmentedFrame {
    /// The individual packets (header + payload) ready for transmission.
    pub packets: Vec<VideoPacket>,
}

/// Fragment a video frame into MTU-sized packets with headers.
///
/// Each fragment gets a [`VideoPacketHeader`] with the correct `fragment_index`
/// and `fragment_count`. The `sequence` number is assigned monotonically
/// starting from `start_sequence`.
///
/// # Arguments
///
/// * `frame_data` — The encoded video frame (e.g., H.265 NALUs).
/// * `frame_number` — Monotonic frame counter.
/// * `frame_type` — [`FRAME_TYPE_I`] or [`FRAME_TYPE_P`].
/// * `timestamp_ms` — Sender timestamp in milliseconds.
/// * `start_sequence` — Sequence number for the first fragment. Subsequent
///   fragments get `start_sequence + 1`, etc.
/// * `fec_group_id` — FEC group identifier for this frame's fragments.
///
/// # Returns
///
/// A [`FragmentedFrame`] containing one packet per fragment. An empty
/// `frame_data` produces a single packet with zero-length payload.
pub fn fragment_frame(
    frame_data: &[u8],
    frame_number: u32,
    frame_type: u8,
    timestamp_ms: u32,
    start_sequence: u32,
    fec_group_id: u8,
) -> FragmentedFrame {
    let chunks: Vec<&[u8]> = if frame_data.is_empty() {
        vec![&[]]
    } else {
        frame_data.chunks(MAX_PAYLOAD_SIZE).collect()
    };
    let fragment_count = chunks.len() as u16;

    let packets = chunks
        .iter()
        .enumerate()
        .map(|(i, chunk)| {
            let header = VideoPacketHeader {
                sequence: start_sequence.wrapping_add(i as u32),
                frame_number,
                fragment_index: i as u16,
                fragment_count,
                frame_type,
                fec_group_id,
                fec_data_count: fragment_count as u8,
                fec_parity_count: 0, // Set by FecEncoder when parity is added
                timestamp_ms,
                payload_length: chunk.len() as u32,
            };
            VideoPacket {
                header,
                payload: chunk.to_vec(),
            }
        })
        .collect();

    FragmentedFrame { packets }
}

/// Fragment a video frame and append FEC parity packets.
///
/// This is a convenience wrapper around [`fragment_frame`] that runs the
/// resulting packets through an [`FecEncoder`] to generate XOR parity.
///
/// # Arguments
///
/// Same as [`fragment_frame`], plus:
/// * `encoder` — The [`FecEncoder`] to use. If `None`, no parity is added.
///
/// # Returns
///
/// A [`FragmentedFrame`] containing data packets followed by parity packet(s).
pub fn fragment_frame_with_fec(
    frame_data: &[u8],
    frame_number: u32,
    frame_type: u8,
    timestamp_ms: u32,
    start_sequence: u32,
    encoder: Option<&mut FecEncoder>,
) -> FragmentedFrame {
    // Use encoder's next_group_id if available, otherwise 0.
    let fec_group_id = encoder
        .as_ref()
        .map(|e| e.next_group_id)
        .unwrap_or(0);

    let fragmented = fragment_frame(
        frame_data,
        frame_number,
        frame_type,
        timestamp_ms,
        start_sequence,
        fec_group_id,
    );

    match encoder {
        Some(enc) => FragmentedFrame {
            packets: enc.encode(fragmented.packets),
        },
        None => fragmented,
    }
}

/// Reassembly buffer for collecting fragments of a single frame.
struct FrameAssembly {
    /// Expected number of fragments.
    fragment_count: u16,
    /// Received fragments indexed by fragment_index.
    fragments: HashMap<u16, Vec<u8>>,
    /// Total payload bytes received so far.
    total_bytes: usize,
}

impl FrameAssembly {
    fn new(fragment_count: u16) -> Self {
        Self {
            fragment_count,
            fragments: HashMap::with_capacity(fragment_count as usize),
            total_bytes: 0,
        }
    }

    /// Insert a fragment. Returns `true` if the frame is now complete.
    fn insert(&mut self, index: u16, payload: Vec<u8>) -> bool {
        if index >= self.fragment_count {
            return false;
        }
        self.total_bytes += payload.len();
        self.fragments.insert(index, payload);
        self.fragments.len() == self.fragment_count as usize
    }

    /// Assemble the complete frame from collected fragments.
    /// Returns `None` if not all fragments have been received.
    fn assemble(&self) -> Option<Vec<u8>> {
        if self.fragments.len() != self.fragment_count as usize {
            return None;
        }
        let mut frame = Vec::with_capacity(self.total_bytes);
        for i in 0..self.fragment_count {
            let fragment = self.fragments.get(&i)?;
            frame.extend_from_slice(fragment);
        }
        Some(frame)
    }
}

/// Reassembles fragmented video packets back into complete frames.
///
/// Maintains per-frame assembly buffers keyed by `frame_number`. Once all
/// fragments for a frame arrive, the frame data can be retrieved via
/// [`reassemble`](Self::reassemble).
///
/// Old incomplete frames are automatically purged when the frame number
/// advances beyond the retention window.
pub struct FrameReassembler {
    /// In-progress frame assemblies, keyed by frame_number.
    assemblies: HashMap<u32, FrameAssembly>,
    /// The highest frame_number that has been fully reassembled.
    last_completed_frame: Option<u32>,
    /// Maximum number of in-progress assemblies before pruning old ones.
    max_pending_frames: usize,
}

impl FrameReassembler {
    /// Create a new reassembler.
    ///
    /// `max_pending_frames` controls how many incomplete frames are kept
    /// in memory before the oldest are discarded. A reasonable default is
    /// 16 (about 0.5 seconds at 30fps).
    pub fn new(max_pending_frames: usize) -> Self {
        Self {
            assemblies: HashMap::new(),
            last_completed_frame: None,
            max_pending_frames,
        }
    }

    /// Feed a received packet into the reassembler.
    ///
    /// Returns `Some(frame_data)` if this packet completed a frame.
    /// Returns `None` if more fragments are needed.
    pub fn reassemble(&mut self, packet: &VideoPacket) -> Option<Vec<u8>> {
        let frame_number = packet.header.frame_number;

        // Discard packets for frames older than the last completed one.
        if let Some(last) = self.last_completed_frame {
            if frame_number <= last {
                return None;
            }
        }

        // Prune old assemblies if we have too many pending.
        if self.assemblies.len() >= self.max_pending_frames
            && !self.assemblies.contains_key(&frame_number)
        {
            // Remove the oldest frame_number.
            if let Some(&oldest) = self.assemblies.keys().min() {
                self.assemblies.remove(&oldest);
            }
        }

        let assembly = self
            .assemblies
            .entry(frame_number)
            .or_insert_with(|| FrameAssembly::new(packet.header.fragment_count));

        let complete =
            assembly.insert(packet.header.fragment_index, packet.payload.clone());

        if complete {
            let result = assembly.assemble();
            self.assemblies.remove(&frame_number);
            self.last_completed_frame = Some(frame_number);
            result
        } else {
            None
        }
    }

    /// Returns the number of frames currently being assembled.
    pub fn pending_frame_count(&self) -> usize {
        self.assemblies.len()
    }

    /// Returns the last completed frame number, if any.
    pub fn last_completed_frame(&self) -> Option<u32> {
        self.last_completed_frame
    }
}

/// Reed-Solomon FEC encoder.
///
/// Takes a set of data packets (fragments of a video frame) and produces
/// additional parity packets. Any K of (K + R) packets suffice to recover
/// the original K data packets.
///
/// # Current Status
///
/// Stubbed — the actual Reed-Solomon implementation requires adding
/// `reed-solomon-erasure` (or `reed-solomon-simd`) to `Cargo.toml`.
pub struct FecEncoder {
    /// FEC overhead ratio. 0.1 = 10% parity packets.
    fec_ratio: f32,
    /// Next FEC group ID to assign.
    next_group_id: u8,
}

impl FecEncoder {
    /// Create a new FEC encoder with the given parity ratio.
    ///
    /// `fec_ratio` controls the amount of redundancy:
    /// - 0.1 = 10% overhead (1 parity per 10 data packets)
    /// - 0.2 = 20% overhead (recommended for keyframes)
    /// - 0.3 = 30% overhead (aggressive, for very lossy networks)
    pub fn new(fec_ratio: f32) -> Self {
        Self {
            fec_ratio: fec_ratio.clamp(0.0, 1.0),
            next_group_id: 0,
        }
    }

    /// Get the current FEC ratio.
    pub fn fec_ratio(&self) -> f32 {
        self.fec_ratio
    }

    /// Update the FEC ratio adaptively based on observed packet loss.
    pub fn set_fec_ratio(&mut self, ratio: f32) {
        self.fec_ratio = ratio.clamp(0.0, 1.0);
    }

    /// Generate a single XOR parity packet from a slice of data packets.
    ///
    /// All payloads are XOR'd together byte-by-byte, with shorter payloads
    /// zero-padded to match the longest. The resulting parity payload can
    /// recover any single missing data packet via XOR with the remaining
    /// data packets.
    ///
    /// # Arguments
    ///
    /// * `data_packets` — The data packets in this FEC group.
    /// * `group_id` — FEC group identifier.
    /// * `next_sequence` — Sequence number for the parity packet.
    ///
    /// # Returns
    ///
    /// A [`VideoPacket`] with `frame_type = FRAME_TYPE_PARITY` (2) containing
    /// the XOR parity payload, or `None` if `data_packets` is empty.
    pub fn generate_parity(
        data_packets: &[VideoPacket],
        group_id: u8,
        next_sequence: u32,
    ) -> Option<VideoPacket> {
        if data_packets.is_empty() {
            return None;
        }

        // Find the maximum payload length for zero-padding.
        let max_len = data_packets
            .iter()
            .map(|p| p.payload.len())
            .max()
            .unwrap_or(0);

        // XOR all payloads together, padding shorter ones with zeros.
        let mut parity = vec![0u8; max_len];
        for packet in data_packets {
            for (i, &byte) in packet.payload.iter().enumerate() {
                parity[i] ^= byte;
            }
            // Bytes beyond packet.payload.len() are implicitly XOR'd with 0
            // (no-op), so no explicit padding needed.
        }

        let data_count = data_packets.len() as u8;
        let header = VideoPacketHeader {
            sequence: next_sequence,
            frame_number: data_packets[0].header.frame_number,
            fragment_index: data_count as u16, // parity follows data fragments
            fragment_count: data_packets[0].header.fragment_count,
            frame_type: FRAME_TYPE_PARITY,
            fec_group_id: group_id,
            fec_data_count: data_count,
            fec_parity_count: 1,
            timestamp_ms: data_packets[0].header.timestamp_ms,
            payload_length: parity.len() as u32,
        };

        Some(VideoPacket {
            header,
            payload: parity,
        })
    }

    /// Encode a set of data packets, producing an additional XOR parity packet.
    ///
    /// The input `packets` are the data fragments of a single video frame
    /// (as produced by [`fragment_frame`]). This method:
    ///
    /// 1. Assigns an FEC group ID to all packets.
    /// 2. Generates 1 XOR parity packet (if `fec_ratio > 0` and there are
    ///    data packets).
    /// 3. Updates `fec_data_count` and `fec_parity_count` in all headers.
    /// 4. Returns the combined data + parity packets.
    pub fn encode(&mut self, mut packets: Vec<VideoPacket>) -> Vec<VideoPacket> {
        if packets.is_empty() {
            return packets;
        }

        let group_id = self.next_group_id;
        self.next_group_id = self.next_group_id.wrapping_add(1);

        let data_count = packets.len() as u8;

        // With XOR FEC we can generate at most 1 parity packet.
        // Generate it if the ratio indicates any parity is desired.
        let parity_count = if self.fec_ratio > 0.0 { 1u8 } else { 0u8 };

        // Update all data packet headers with FEC group info.
        for packet in &mut packets {
            packet.header.fec_group_id = group_id;
            packet.header.fec_data_count = data_count;
            packet.header.fec_parity_count = parity_count;
        }

        // Generate XOR parity packet if requested.
        if parity_count > 0 {
            let next_seq = packets
                .last()
                .unwrap()
                .header
                .sequence
                .wrapping_add(1);
            if let Some(parity_packet) =
                Self::generate_parity(&packets, group_id, next_seq)
            {
                packets.push(parity_packet);
            }
        }

        packets
    }
}

/// XOR-based FEC decoder.
///
/// Given the data packets and optional parity packet from an FEC group,
/// reconstructs a single missing data packet using XOR recovery.
///
/// # Recovery Capability
///
/// - All data packets present: returns them directly (no recovery needed).
/// - Exactly 1 data packet missing + parity present: recovers via XOR.
/// - 2+ data packets missing: returns `None` (XOR FEC cannot recover).
pub struct FecDecoder;

impl FecDecoder {
    /// Create a new FEC decoder.
    pub fn new() -> Self {
        Self
    }

    /// Attempt to recover missing data packets using XOR parity.
    ///
    /// # Arguments
    ///
    /// * `received` — Slots for the FEC group: indices `0..data_count` are
    ///   data packet payloads, and index `data_count` (if present) is the
    ///   parity payload. `None` entries indicate missing packets.
    /// * `data_count` — Number of data packets in the group.
    /// * `_parity_count` — Number of parity packets (expected to be 0 or 1
    ///   for XOR FEC).
    ///
    /// # Returns
    ///
    /// `Some(data_payloads)` — a vector of `data_count` payloads in order
    /// if all data is available or recovery succeeded. `None` if recovery
    /// is impossible (2+ missing data packets, or 1 missing without parity).
    pub fn decode(
        &self,
        received: &[Option<Vec<u8>>],
        data_count: usize,
        _parity_count: usize,
    ) -> Option<Vec<Vec<u8>>> {
        if data_count == 0 {
            return Some(vec![]);
        }

        // Separate data slots from parity slot.
        let data_slots = &received[..data_count.min(received.len())];
        let parity_slot = received.get(data_count).and_then(|s| s.as_ref());

        // Count missing data packets.
        let mut missing_index = None;
        let mut missing_count = 0;
        for (i, slot) in data_slots.iter().enumerate() {
            if slot.is_none() {
                missing_count += 1;
                missing_index = Some(i);
            }
        }

        match missing_count {
            0 => {
                // All data packets present — just return them.
                let payloads = data_slots
                    .iter()
                    .map(|s| s.as_ref().unwrap().clone())
                    .collect();
                Some(payloads)
            }
            1 => {
                // Exactly 1 missing — recover using XOR parity.
                let parity = parity_slot?;
                let missing_idx = missing_index.unwrap();

                // XOR parity with all present data packets to recover
                // the missing one.
                let mut recovered = parity.clone();
                for (i, slot) in data_slots.iter().enumerate() {
                    if i == missing_idx {
                        continue;
                    }
                    let payload = slot.as_ref().unwrap();
                    // XOR each byte; if recovered is shorter than payload,
                    // extend it; if payload is shorter, only XOR up to its
                    // length.
                    if recovered.len() < payload.len() {
                        recovered.resize(payload.len(), 0);
                    }
                    for (j, &byte) in payload.iter().enumerate() {
                        recovered[j] ^= byte;
                    }
                }

                // Build the result with the recovered packet in place.
                let mut payloads: Vec<Vec<u8>> = Vec::with_capacity(data_count);
                for (i, slot) in data_slots.iter().enumerate() {
                    if i == missing_idx {
                        payloads.push(recovered.clone());
                    } else {
                        payloads.push(slot.as_ref().unwrap().clone());
                    }
                }
                Some(payloads)
            }
            _ => {
                // 2+ missing — XOR FEC cannot recover.
                None
            }
        }
    }

    /// Higher-level recovery: given a set of received [`VideoPacket`]s for
    /// a single FEC group, attempt to produce the complete set of data
    /// payloads in fragment order.
    ///
    /// This method arranges received packets into the slot array expected
    /// by [`decode`](Self::decode) and handles parity packet identification
    /// via `frame_type == FRAME_TYPE_PARITY`.
    ///
    /// # Returns
    ///
    /// `Some(data_payloads)` in fragment order if all data is present or
    /// recovery succeeded. `None` otherwise.
    pub fn try_recover(
        &self,
        packets: &[VideoPacket],
        data_count: usize,
    ) -> Option<Vec<Vec<u8>>> {
        if data_count == 0 {
            return Some(vec![]);
        }

        // Build slot array: data_count data slots + 1 parity slot.
        let mut slots: Vec<Option<Vec<u8>>> = vec![None; data_count + 1];

        for packet in packets {
            if packet.header.frame_type == FRAME_TYPE_PARITY {
                // Parity packet goes in the last slot.
                slots[data_count] = Some(packet.payload.clone());
            } else {
                let idx = packet.header.fragment_index as usize;
                if idx < data_count {
                    slots[idx] = Some(packet.payload.clone());
                }
            }
        }

        self.decode(&slots, data_count, 1)
    }
}

impl Default for FecDecoder {
    fn default() -> Self {
        Self::new()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    // ---------------------------------------------------------------
    // VideoPacketHeader tests
    // ---------------------------------------------------------------

    #[test]
    fn header_size_is_24_bytes() {
        assert_eq!(
            std::mem::size_of::<VideoPacketHeader>(),
            HEADER_SIZE,
            "VideoPacketHeader must be exactly 24 bytes for wire compatibility"
        );
    }

    #[test]
    fn header_serialization_round_trip() {
        let original = VideoPacketHeader {
            sequence: 42,
            frame_number: 100,
            fragment_index: 3,
            fragment_count: 10,
            frame_type: FRAME_TYPE_I,
            fec_group_id: 7,
            fec_data_count: 10,
            fec_parity_count: 2,
            timestamp_ms: 1_234_567,
            payload_length: 1376,
        };

        let bytes = original.to_bytes();
        assert_eq!(bytes.len(), HEADER_SIZE);

        let decoded = VideoPacketHeader::from_bytes(&bytes)
            .expect("from_bytes should succeed for valid data");
        assert_eq!(original, decoded);
    }

    #[test]
    fn header_serialization_round_trip_zeroes() {
        let original = VideoPacketHeader {
            sequence: 0,
            frame_number: 0,
            fragment_index: 0,
            fragment_count: 0,
            frame_type: 0,
            fec_group_id: 0,
            fec_data_count: 0,
            fec_parity_count: 0,
            timestamp_ms: 0,
            payload_length: 0,
        };

        let bytes = original.to_bytes();
        assert_eq!(bytes, [0u8; HEADER_SIZE]);

        let decoded = VideoPacketHeader::from_bytes(&bytes).unwrap();
        assert_eq!(original, decoded);
    }

    #[test]
    fn header_serialization_round_trip_max_values() {
        let original = VideoPacketHeader {
            sequence: u32::MAX,
            frame_number: u32::MAX,
            fragment_index: u16::MAX,
            fragment_count: u16::MAX,
            frame_type: u8::MAX,
            fec_group_id: u8::MAX,
            fec_data_count: u8::MAX,
            fec_parity_count: u8::MAX,
            timestamp_ms: u32::MAX,
            payload_length: u32::MAX,
        };

        let bytes = original.to_bytes();
        let decoded = VideoPacketHeader::from_bytes(&bytes).unwrap();
        assert_eq!(original, decoded);
    }

    #[test]
    fn header_from_bytes_rejects_short_input() {
        let short = [0u8; 23]; // One byte too short
        assert!(
            VideoPacketHeader::from_bytes(&short).is_none(),
            "from_bytes must return None for data shorter than 24 bytes"
        );

        assert!(VideoPacketHeader::from_bytes(&[]).is_none());
    }

    #[test]
    fn header_from_bytes_accepts_extra_bytes() {
        // from_bytes should work even if there are extra bytes after the header
        // (as there would be in a full packet with payload).
        let header = VideoPacketHeader {
            sequence: 1,
            frame_number: 2,
            fragment_index: 0,
            fragment_count: 1,
            frame_type: FRAME_TYPE_P,
            fec_group_id: 0,
            fec_data_count: 1,
            fec_parity_count: 0,
            timestamp_ms: 500,
            payload_length: 100,
        };
        let mut data = header.to_bytes().to_vec();
        data.extend_from_slice(&[0xAB; 100]); // Extra payload bytes

        let decoded = VideoPacketHeader::from_bytes(&data).unwrap();
        assert_eq!(header, decoded);
    }

    #[test]
    fn frame_type_encoding() {
        assert_eq!(FRAME_TYPE_P, 0, "P-frame type must be 0");
        assert_eq!(FRAME_TYPE_I, 1, "I-frame type must be 1");

        // Verify frame_type survives round-trip at the boundary values.
        for ft in [FRAME_TYPE_P, FRAME_TYPE_I, 255u8] {
            let header = VideoPacketHeader {
                sequence: 0,
                frame_number: 0,
                fragment_index: 0,
                fragment_count: 1,
                frame_type: ft,
                fec_group_id: 0,
                fec_data_count: 1,
                fec_parity_count: 0,
                timestamp_ms: 0,
                payload_length: 0,
            };
            let decoded = VideoPacketHeader::from_bytes(&header.to_bytes()).unwrap();
            assert_eq!(decoded.frame_type, ft);
        }
    }

    // ---------------------------------------------------------------
    // Fragmentation tests
    // ---------------------------------------------------------------

    #[test]
    fn fragment_small_frame_single_packet() {
        let frame_data = vec![0xAA; 100]; // Fits in one fragment
        let result = fragment_frame(&frame_data, 1, FRAME_TYPE_P, 1000, 0, 0);

        assert_eq!(result.packets.len(), 1);
        assert_eq!(result.packets[0].header.fragment_index, 0);
        assert_eq!(result.packets[0].header.fragment_count, 1);
        assert_eq!(result.packets[0].header.frame_number, 1);
        assert_eq!(result.packets[0].header.frame_type, FRAME_TYPE_P);
        assert_eq!(result.packets[0].header.timestamp_ms, 1000);
        assert_eq!(result.packets[0].header.payload_length, 100);
        assert_eq!(result.packets[0].payload, frame_data);
    }

    #[test]
    fn fragment_large_frame_multiple_packets() {
        // A 50KB frame should produce ceil(50000 / 1376) = 37 fragments.
        let frame_data = vec![0xBB; 50_000];
        let expected_fragments = (50_000 + MAX_PAYLOAD_SIZE - 1) / MAX_PAYLOAD_SIZE;
        assert_eq!(expected_fragments, 37);

        let result =
            fragment_frame(&frame_data, 42, FRAME_TYPE_I, 2000, 100, 5);

        assert_eq!(result.packets.len(), expected_fragments);

        // Verify fragment indices and counts.
        for (i, packet) in result.packets.iter().enumerate() {
            assert_eq!(packet.header.fragment_index, i as u16);
            assert_eq!(packet.header.fragment_count, expected_fragments as u16);
            assert_eq!(packet.header.frame_number, 42);
            assert_eq!(packet.header.frame_type, FRAME_TYPE_I);
            assert_eq!(packet.header.timestamp_ms, 2000);
        }

        // Verify all payloads concatenate to the original frame.
        let mut reassembled = Vec::new();
        for packet in &result.packets {
            assert_eq!(packet.header.payload_length, packet.payload.len() as u32);
            reassembled.extend_from_slice(&packet.payload);
        }
        assert_eq!(reassembled, frame_data);

        // Last fragment may be shorter.
        let last = result.packets.last().unwrap();
        assert_eq!(last.payload.len(), 50_000 % MAX_PAYLOAD_SIZE);
    }

    #[test]
    fn fragment_exact_mtu_boundary() {
        // Frame that is exactly MAX_PAYLOAD_SIZE — should produce 1 fragment.
        let frame_data = vec![0xCC; MAX_PAYLOAD_SIZE];
        let result = fragment_frame(&frame_data, 0, FRAME_TYPE_P, 0, 0, 0);
        assert_eq!(result.packets.len(), 1);
        assert_eq!(result.packets[0].payload.len(), MAX_PAYLOAD_SIZE);

        // Frame that is MAX_PAYLOAD_SIZE + 1 — should produce 2 fragments.
        let frame_data = vec![0xDD; MAX_PAYLOAD_SIZE + 1];
        let result = fragment_frame(&frame_data, 0, FRAME_TYPE_P, 0, 0, 0);
        assert_eq!(result.packets.len(), 2);
        assert_eq!(result.packets[0].payload.len(), MAX_PAYLOAD_SIZE);
        assert_eq!(result.packets[1].payload.len(), 1);
    }

    #[test]
    fn fragment_empty_frame() {
        let result = fragment_frame(&[], 0, FRAME_TYPE_P, 0, 0, 0);
        assert_eq!(result.packets.len(), 1);
        assert_eq!(result.packets[0].header.fragment_count, 1);
        assert_eq!(result.packets[0].header.payload_length, 0);
        assert!(result.packets[0].payload.is_empty());
    }

    #[test]
    fn sequence_numbers_are_monotonic() {
        let frame_data = vec![0xEE; MAX_PAYLOAD_SIZE * 5]; // 5 fragments
        let start_seq = 1000u32;
        let result =
            fragment_frame(&frame_data, 0, FRAME_TYPE_P, 0, start_seq, 0);

        for (i, packet) in result.packets.iter().enumerate() {
            assert_eq!(
                packet.header.sequence,
                start_seq + i as u32,
                "Sequence numbers must be monotonically increasing"
            );
        }
    }

    #[test]
    fn sequence_numbers_wrap_at_u32_max() {
        let frame_data = vec![0xFF; MAX_PAYLOAD_SIZE * 3];
        let start_seq = u32::MAX - 1;
        let result =
            fragment_frame(&frame_data, 0, FRAME_TYPE_P, 0, start_seq, 0);

        assert_eq!(result.packets[0].header.sequence, u32::MAX - 1);
        assert_eq!(result.packets[1].header.sequence, u32::MAX);
        assert_eq!(result.packets[2].header.sequence, 0); // Wraps
    }

    // ---------------------------------------------------------------
    // VideoPacket serialization tests
    // ---------------------------------------------------------------

    #[test]
    fn video_packet_round_trip() {
        let packet = VideoPacket {
            header: VideoPacketHeader {
                sequence: 7,
                frame_number: 3,
                fragment_index: 0,
                fragment_count: 1,
                frame_type: FRAME_TYPE_I,
                fec_group_id: 1,
                fec_data_count: 1,
                fec_parity_count: 0,
                timestamp_ms: 12345,
                payload_length: 5,
            },
            payload: vec![1, 2, 3, 4, 5],
        };

        let bytes = packet.to_bytes();
        assert_eq!(bytes.len(), HEADER_SIZE + 5);

        let decoded = VideoPacket::from_bytes(&bytes).unwrap();
        assert_eq!(decoded.header, packet.header);
        assert_eq!(decoded.payload, packet.payload);
    }

    #[test]
    fn video_packet_from_bytes_rejects_truncated() {
        // Header says 100 bytes payload but only 10 are present.
        let header = VideoPacketHeader {
            sequence: 0,
            frame_number: 0,
            fragment_index: 0,
            fragment_count: 1,
            frame_type: 0,
            fec_group_id: 0,
            fec_data_count: 1,
            fec_parity_count: 0,
            timestamp_ms: 0,
            payload_length: 100,
        };
        let mut data = header.to_bytes().to_vec();
        data.extend_from_slice(&[0u8; 10]); // Only 10 bytes, not 100

        assert!(VideoPacket::from_bytes(&data).is_none());
    }

    // ---------------------------------------------------------------
    // Reassembly tests
    // ---------------------------------------------------------------

    #[test]
    fn reassemble_single_fragment_frame() {
        let mut reassembler = FrameReassembler::new(16);
        let frame_data = b"hello world";

        let fragmented =
            fragment_frame(frame_data, 1, FRAME_TYPE_P, 100, 0, 0);
        assert_eq!(fragmented.packets.len(), 1);

        let result = reassembler.reassemble(&fragmented.packets[0]);
        assert_eq!(result, Some(frame_data.to_vec()));
    }

    #[test]
    fn reassemble_multi_fragment_frame() {
        let mut reassembler = FrameReassembler::new(16);
        let frame_data = vec![0xAA; MAX_PAYLOAD_SIZE * 3 + 500];

        let fragmented =
            fragment_frame(&frame_data, 1, FRAME_TYPE_I, 200, 0, 0);
        assert_eq!(fragmented.packets.len(), 4);

        // Feed first 3 packets — not yet complete.
        for packet in &fragmented.packets[..3] {
            assert_eq!(reassembler.reassemble(packet), None);
        }

        // Feed last packet — frame should be complete.
        let result = reassembler.reassemble(&fragmented.packets[3]);
        assert_eq!(result, Some(frame_data));
    }

    #[test]
    fn reassemble_out_of_order_fragments() {
        let mut reassembler = FrameReassembler::new(16);
        let frame_data = vec![0xBB; MAX_PAYLOAD_SIZE * 3];

        let fragmented =
            fragment_frame(&frame_data, 5, FRAME_TYPE_P, 300, 0, 0);
        assert_eq!(fragmented.packets.len(), 3);

        // Send fragments in reverse order.
        assert_eq!(reassembler.reassemble(&fragmented.packets[2]), None);
        assert_eq!(reassembler.reassemble(&fragmented.packets[0]), None);
        let result = reassembler.reassemble(&fragmented.packets[1]);
        assert_eq!(result, Some(frame_data));
    }

    #[test]
    fn reassemble_discards_old_frames() {
        let mut reassembler = FrameReassembler::new(16);

        // Complete frame 10.
        let frame10 = fragment_frame(b"frame10", 10, FRAME_TYPE_P, 0, 0, 0);
        let result = reassembler.reassemble(&frame10.packets[0]);
        assert_eq!(result, Some(b"frame10".to_vec()));

        // Stale packet for frame 5 (older than completed frame 10) is discarded.
        let frame5 = fragment_frame(b"frame5", 5, FRAME_TYPE_P, 0, 10, 0);
        let result = reassembler.reassemble(&frame5.packets[0]);
        assert_eq!(result, None, "Packets for old frames should be discarded");
    }

    #[test]
    fn reassemble_multiple_concurrent_frames() {
        let mut reassembler = FrameReassembler::new(16);
        let frame_a_data = vec![0xAA; MAX_PAYLOAD_SIZE * 2];
        let frame_b_data = vec![0xBB; MAX_PAYLOAD_SIZE * 2];

        let frame_a = fragment_frame(&frame_a_data, 1, FRAME_TYPE_I, 100, 0, 0);
        let frame_b = fragment_frame(&frame_b_data, 2, FRAME_TYPE_P, 133, 10, 1);

        // Interleave fragments from both frames.
        assert_eq!(reassembler.reassemble(&frame_a.packets[0]), None);
        assert_eq!(reassembler.reassemble(&frame_b.packets[0]), None);
        assert_eq!(reassembler.pending_frame_count(), 2);

        // Complete frame A.
        let result = reassembler.reassemble(&frame_a.packets[1]);
        assert_eq!(result, Some(frame_a_data));

        // Complete frame B.
        let result = reassembler.reassemble(&frame_b.packets[1]);
        assert_eq!(result, Some(frame_b_data));

        assert_eq!(reassembler.pending_frame_count(), 0);
    }

    #[test]
    fn reassemble_prunes_when_too_many_pending() {
        let mut reassembler = FrameReassembler::new(2); // Only 2 pending allowed

        // Start assembly for frames 1, 2, 3 (each multi-fragment).
        let f1 = fragment_frame(&vec![0; MAX_PAYLOAD_SIZE * 2], 1, FRAME_TYPE_P, 0, 0, 0);
        let f2 = fragment_frame(&vec![0; MAX_PAYLOAD_SIZE * 2], 2, FRAME_TYPE_P, 0, 10, 0);
        let f3 = fragment_frame(&vec![0; MAX_PAYLOAD_SIZE * 2], 3, FRAME_TYPE_P, 0, 20, 0);

        reassembler.reassemble(&f1.packets[0]); // Pending: {1}
        reassembler.reassemble(&f2.packets[0]); // Pending: {1, 2}
        // Adding frame 3 should prune frame 1 (oldest).
        reassembler.reassemble(&f3.packets[0]); // Pending: {2, 3}

        assert_eq!(reassembler.pending_frame_count(), 2);

        // Frame 1's second fragment arrives — but frame 1 was pruned.
        let result = reassembler.reassemble(&f1.packets[1]);
        assert_eq!(result, None, "Pruned frame should not reassemble");
    }

    // ---------------------------------------------------------------
    // FEC encoder tests
    // ---------------------------------------------------------------

    #[test]
    fn fec_encoder_assigns_group_ids() {
        let mut encoder = FecEncoder::new(0.1);

        let frame1 = fragment_frame(b"frame1", 1, FRAME_TYPE_P, 0, 0, 0);
        let packets1 = encoder.encode(frame1.packets);
        let gid1 = packets1[0].header.fec_group_id;

        let frame2 = fragment_frame(b"frame2", 2, FRAME_TYPE_P, 0, 1, 0);
        let packets2 = encoder.encode(frame2.packets);
        let gid2 = packets2[0].header.fec_group_id;

        assert_ne!(gid1, gid2, "Each encode call should get a unique group ID");
        assert_eq!(gid2, gid1.wrapping_add(1));
    }

    #[test]
    fn fec_encoder_sets_data_count() {
        let mut encoder = FecEncoder::new(0.2);

        let frame = fragment_frame(&vec![0; MAX_PAYLOAD_SIZE * 5], 1, FRAME_TYPE_I, 0, 0, 0);
        assert_eq!(frame.packets.len(), 5);

        let packets = encoder.encode(frame.packets);

        // data packets should have fec_data_count = 5
        for packet in &packets[..5] {
            assert_eq!(packet.header.fec_data_count, 5);
        }
    }

    #[test]
    fn fec_encoder_ratio_clamped() {
        let encoder = FecEncoder::new(2.0); // Above 1.0
        assert!(encoder.fec_ratio() <= 1.0);

        let encoder = FecEncoder::new(-0.5); // Below 0.0
        assert!(encoder.fec_ratio() >= 0.0);
    }

    #[test]
    fn fec_encoder_generates_parity_packet() {
        let mut encoder = FecEncoder::new(0.5);

        let frame = fragment_frame(b"hello", 1, FRAME_TYPE_P, 1000, 0, 0);
        assert_eq!(frame.packets.len(), 1); // 1 data packet

        let packets = encoder.encode(frame.packets);
        // Should have 1 data + 1 parity = 2 packets
        assert_eq!(packets.len(), 2);

        // Last packet is the parity packet.
        let parity = &packets[1];
        assert_eq!(
            parity.header.frame_type, FRAME_TYPE_PARITY,
            "Parity packet must have frame_type = 2"
        );
        assert_eq!(parity.header.fec_data_count, 1);
        assert_eq!(parity.header.fec_parity_count, 1);

        // For a single data packet, parity = data XOR data... which is just
        // the data itself (XOR with initial zeros).
        assert_eq!(parity.payload, b"hello");
    }

    #[test]
    fn fec_encoder_no_parity_when_ratio_zero() {
        let mut encoder = FecEncoder::new(0.0);

        let frame = fragment_frame(b"data", 1, FRAME_TYPE_P, 0, 0, 0);
        let packets = encoder.encode(frame.packets);

        // No parity should be added.
        assert_eq!(packets.len(), 1);
        assert_eq!(packets[0].header.fec_parity_count, 0);
    }

    #[test]
    fn fec_xor_parity_correctness() {
        // Manual XOR test with known payloads.
        let p1 = VideoPacket {
            header: VideoPacketHeader {
                sequence: 0, frame_number: 1, fragment_index: 0,
                fragment_count: 3, frame_type: FRAME_TYPE_P,
                fec_group_id: 0, fec_data_count: 3, fec_parity_count: 0,
                timestamp_ms: 0, payload_length: 4,
            },
            payload: vec![0xAA, 0xBB, 0xCC, 0xDD],
        };
        let p2 = VideoPacket {
            header: VideoPacketHeader {
                sequence: 1, frame_number: 1, fragment_index: 1,
                fragment_count: 3, frame_type: FRAME_TYPE_P,
                fec_group_id: 0, fec_data_count: 3, fec_parity_count: 0,
                timestamp_ms: 0, payload_length: 4,
            },
            payload: vec![0x11, 0x22, 0x33, 0x44],
        };
        let p3 = VideoPacket {
            header: VideoPacketHeader {
                sequence: 2, frame_number: 1, fragment_index: 2,
                fragment_count: 3, frame_type: FRAME_TYPE_P,
                fec_group_id: 0, fec_data_count: 3, fec_parity_count: 0,
                timestamp_ms: 0, payload_length: 4,
            },
            payload: vec![0xFF, 0x00, 0xFF, 0x00],
        };

        let parity = FecEncoder::generate_parity(&[p1, p2, p3], 0, 3).unwrap();

        // Expected: 0xAA^0x11^0xFF, 0xBB^0x22^0x00, 0xCC^0x33^0xFF, 0xDD^0x44^0x00
        let expected = vec![
            0xAA ^ 0x11 ^ 0xFF,
            0xBB ^ 0x22 ^ 0x00,
            0xCC ^ 0x33 ^ 0xFF,
            0xDD ^ 0x44 ^ 0x00,
        ];
        assert_eq!(parity.payload, expected);
        assert_eq!(parity.header.frame_type, FRAME_TYPE_PARITY);
    }

    #[test]
    fn fec_parity_header_has_correct_frame_type() {
        let mut encoder = FecEncoder::new(0.5);
        let frame = fragment_frame(&vec![0xAB; 100], 5, FRAME_TYPE_I, 500, 0, 0);
        let packets = encoder.encode(frame.packets);

        let parity = packets.last().unwrap();
        assert_eq!(parity.header.frame_type, FRAME_TYPE_PARITY);
        assert_eq!(parity.header.frame_number, 5);
        assert_eq!(parity.header.timestamp_ms, 500);
    }

    #[test]
    fn fec_generate_parity_empty_group() {
        let result = FecEncoder::generate_parity(&[], 0, 0);
        assert!(result.is_none(), "Empty group should produce no parity");
    }

    #[test]
    fn fec_parity_with_different_payload_sizes() {
        // Test that shorter payloads are zero-padded before XOR.
        let short = VideoPacket {
            header: VideoPacketHeader {
                sequence: 0, frame_number: 1, fragment_index: 0,
                fragment_count: 2, frame_type: FRAME_TYPE_P,
                fec_group_id: 0, fec_data_count: 2, fec_parity_count: 0,
                timestamp_ms: 0, payload_length: 2,
            },
            payload: vec![0xAA, 0xBB],
        };
        let long = VideoPacket {
            header: VideoPacketHeader {
                sequence: 1, frame_number: 1, fragment_index: 1,
                fragment_count: 2, frame_type: FRAME_TYPE_P,
                fec_group_id: 0, fec_data_count: 2, fec_parity_count: 0,
                timestamp_ms: 0, payload_length: 4,
            },
            payload: vec![0x11, 0x22, 0x33, 0x44],
        };

        let parity = FecEncoder::generate_parity(&[short, long], 0, 2).unwrap();

        // short is implicitly padded: [0xAA, 0xBB, 0x00, 0x00]
        // XOR with long:              [0x11, 0x22, 0x33, 0x44]
        // Result:                     [0xBB, 0x99, 0x33, 0x44]
        assert_eq!(parity.payload, vec![0xAA ^ 0x11, 0xBB ^ 0x22, 0x33, 0x44]);
        assert_eq!(parity.payload.len(), 4, "Parity length should match longest payload");
    }

    // ---------------------------------------------------------------
    // FEC decoder tests
    // ---------------------------------------------------------------

    #[test]
    fn fec_decoder_all_present_no_recovery_needed() {
        let decoder = FecDecoder::new();
        let received: Vec<Option<Vec<u8>>> = vec![
            Some(vec![1, 2, 3]),
            Some(vec![4, 5, 6]),
            Some(vec![7, 8, 9]),   // parity slot (index = data_count)
        ];
        let result = decoder.decode(&received, 2, 1);
        assert!(result.is_some());
        let payloads = result.unwrap();
        assert_eq!(payloads.len(), 2);
        assert_eq!(payloads[0], vec![1, 2, 3]);
        assert_eq!(payloads[1], vec![4, 5, 6]);
    }

    #[test]
    fn fec_decoder_recover_single_missing_packet() {
        let decoder = FecDecoder::new();

        // Original data: [0xAA, 0xBB] and [0x11, 0x22]
        // Parity:        [0xAA^0x11, 0xBB^0x22] = [0xBB, 0x99]
        let received: Vec<Option<Vec<u8>>> = vec![
            None,                          // packet 0 missing
            Some(vec![0x11, 0x22]),         // packet 1 present
            Some(vec![0xBB, 0x99]),         // parity present
        ];
        let result = decoder.decode(&received, 2, 1);
        assert!(result.is_some());
        let payloads = result.unwrap();
        assert_eq!(payloads[0], vec![0xAA, 0xBB], "Should recover missing packet 0");
        assert_eq!(payloads[1], vec![0x11, 0x22]);
    }

    #[test]
    fn fec_decoder_recover_second_missing_packet() {
        let decoder = FecDecoder::new();

        // Data: [0xFF] and [0x0F]
        // Parity: [0xFF ^ 0x0F] = [0xF0]
        let received: Vec<Option<Vec<u8>>> = vec![
            Some(vec![0xFF]),  // packet 0 present
            None,              // packet 1 missing
            Some(vec![0xF0]), // parity
        ];
        let result = decoder.decode(&received, 2, 1);
        assert!(result.is_some());
        let payloads = result.unwrap();
        assert_eq!(payloads[0], vec![0xFF]);
        assert_eq!(payloads[1], vec![0x0F], "Should recover missing packet 1");
    }

    #[test]
    fn fec_decoder_two_missing_cannot_recover() {
        let decoder = FecDecoder::new();

        let received: Vec<Option<Vec<u8>>> = vec![
            None,                  // packet 0 missing
            None,                  // packet 1 missing
            Some(vec![0x00]),      // parity present but insufficient
        ];
        let result = decoder.decode(&received, 2, 1);
        assert!(result.is_none(), "Cannot recover with 2 missing packets");
    }

    #[test]
    fn fec_decoder_one_missing_no_parity() {
        let decoder = FecDecoder::new();

        let received: Vec<Option<Vec<u8>>> = vec![
            Some(vec![1, 2, 3]),
            None,               // packet 1 missing
            None,               // parity also missing
        ];
        let result = decoder.decode(&received, 2, 1);
        assert!(result.is_none(), "Cannot recover without parity");
    }

    #[test]
    fn fec_decoder_empty_group() {
        let decoder = FecDecoder::new();
        let received: Vec<Option<Vec<u8>>> = vec![];
        let result = decoder.decode(&received, 0, 0);
        assert_eq!(result, Some(vec![]));
    }

    #[test]
    fn fec_decoder_recover_with_different_payload_sizes() {
        let decoder = FecDecoder::new();

        // Data: [0xAA, 0xBB] (2 bytes) and [0x11, 0x22, 0x33, 0x44] (4 bytes)
        // For parity, short payload is zero-padded: [0xAA, 0xBB, 0x00, 0x00]
        // Parity = [0xAA^0x11, 0xBB^0x22, 0x00^0x33, 0x00^0x44]
        //        = [0xBB, 0x99, 0x33, 0x44]
        let received: Vec<Option<Vec<u8>>> = vec![
            None,                              // packet 0 missing (was 2 bytes)
            Some(vec![0x11, 0x22, 0x33, 0x44]),// packet 1 present
            Some(vec![0xBB, 0x99, 0x33, 0x44]),// parity (4 bytes)
        ];
        let result = decoder.decode(&received, 2, 1);
        assert!(result.is_some());
        let payloads = result.unwrap();
        // Recovered payload will be 4 bytes (parity length), with trailing zeros
        // from the zero-padding. This is expected behavior — the recovered
        // payload includes the padding bytes.
        assert_eq!(payloads[0], vec![0xAA, 0xBB, 0x00, 0x00]);
    }

    // ---------------------------------------------------------------
    // FEC try_recover tests (higher-level API)
    // ---------------------------------------------------------------

    #[test]
    fn fec_try_recover_all_present() {
        let decoder = FecDecoder::new();
        let mut encoder = FecEncoder::new(0.5);

        let frame = fragment_frame(b"test data!", 1, FRAME_TYPE_P, 0, 0, 0);
        let packets = encoder.encode(frame.packets);

        // All packets present (data + parity).
        let result = decoder.try_recover(&packets, 1);
        assert!(result.is_some());
        assert_eq!(result.unwrap()[0], b"test data!");
    }

    #[test]
    fn fec_try_recover_missing_data_packet() {
        let decoder = FecDecoder::new();
        let mut encoder = FecEncoder::new(0.5);

        // Create 3 data packets.
        let frame = fragment_frame(
            &vec![0xAB; MAX_PAYLOAD_SIZE * 3],
            1, FRAME_TYPE_I, 0, 0, 0,
        );
        let packets = encoder.encode(frame.packets);
        assert_eq!(packets.len(), 4); // 3 data + 1 parity

        // Drop the second data packet (index 1).
        let received: Vec<VideoPacket> = packets
            .into_iter()
            .filter(|p| p.header.fragment_index != 1 || p.header.frame_type == FRAME_TYPE_PARITY)
            .collect();
        assert_eq!(received.len(), 3); // 2 data + 1 parity

        let result = decoder.try_recover(&received, 3);
        assert!(result.is_some());
        let payloads = result.unwrap();
        assert_eq!(payloads.len(), 3);

        // All 3 fragments had identical payload (0xAB repeated).
        assert_eq!(payloads[0], vec![0xAB; MAX_PAYLOAD_SIZE]);
        assert_eq!(payloads[1], vec![0xAB; MAX_PAYLOAD_SIZE]);
        assert_eq!(payloads[2], vec![0xAB; MAX_PAYLOAD_SIZE]);
    }

    #[test]
    fn fec_try_recover_two_missing_fails() {
        let decoder = FecDecoder::new();
        let mut encoder = FecEncoder::new(0.5);

        let frame = fragment_frame(
            &vec![0xCD; MAX_PAYLOAD_SIZE * 3],
            1, FRAME_TYPE_P, 0, 0, 0,
        );
        let packets = encoder.encode(frame.packets);
        assert_eq!(packets.len(), 4); // 3 data + 1 parity

        // Drop two data packets.
        let received: Vec<VideoPacket> = packets
            .into_iter()
            .filter(|p| p.header.fragment_index == 0 || p.header.frame_type == FRAME_TYPE_PARITY)
            .collect();
        assert_eq!(received.len(), 2); // 1 data + 1 parity

        let result = decoder.try_recover(&received, 3);
        assert!(result.is_none(), "Cannot recover with 2 missing data packets");
    }

    // ---------------------------------------------------------------
    // Round-trip integration test
    // ---------------------------------------------------------------

    #[test]
    fn fec_round_trip_fragment_add_parity_drop_one_recover_reassemble() {
        // 1. Fragment a frame.
        let original_frame = b"The quick brown fox jumps over the lazy dog. \
            This is a test of the FEC round-trip: fragment, add parity, \
            drop one packet, recover, and reassemble.";

        let mut encoder = FecEncoder::new(0.5);
        let fragmented = fragment_frame_with_fec(
            original_frame,
            42,
            FRAME_TYPE_I,
            12345,
            0,
            Some(&mut encoder),
        );

        // Should have 1 data + 1 parity = 2 packets.
        assert_eq!(fragmented.packets.len(), 2);
        let data_count = fragmented.packets[0].header.fec_data_count as usize;
        assert_eq!(data_count, 1);

        // 2. Simulate dropping the data packet (keep only parity).
        // Actually, we need the parity to recover data. But with 1 data packet
        // the parity IS the data. Let's use a multi-fragment example.

        // Larger frame that produces multiple fragments.
        let large_frame: Vec<u8> = (0..255u8)
            .cycle()
            .take(MAX_PAYLOAD_SIZE * 4 + 100)
            .collect();

        let mut encoder2 = FecEncoder::new(0.5);
        let fragmented2 = fragment_frame_with_fec(
            &large_frame,
            100,
            FRAME_TYPE_I,
            99999,
            0,
            Some(&mut encoder2),
        );

        // 5 data packets + 1 parity = 6 total.
        assert_eq!(fragmented2.packets.len(), 6);
        let data_count2 = fragmented2.packets[0].header.fec_data_count as usize;
        assert_eq!(data_count2, 5);

        // 3. Drop fragment_index=2 (the third data packet).
        let received: Vec<VideoPacket> = fragmented2
            .packets
            .iter()
            .filter(|p| {
                p.header.fragment_index != 2 || p.header.frame_type == FRAME_TYPE_PARITY
            })
            .cloned()
            .collect();
        assert_eq!(received.len(), 5); // 4 data + 1 parity

        // 4. Recover using FEC decoder.
        let decoder = FecDecoder::new();
        let recovered = decoder.try_recover(&received, data_count2);
        assert!(recovered.is_some(), "Should recover with 1 missing packet");
        let payloads = recovered.unwrap();
        assert_eq!(payloads.len(), 5);

        // 5. Reassemble the frame from recovered payloads.
        let mut reassembled = Vec::new();
        for payload in &payloads {
            reassembled.extend_from_slice(payload);
        }

        // The reassembled data should match the original frame.
        // Note: the last fragment may have been padded in parity calculation,
        // but the payload itself is preserved as-is for present packets.
        // The recovered packet (fragment 2) was full-sized (MAX_PAYLOAD_SIZE)
        // so no padding issue.
        assert_eq!(
            &reassembled[..large_frame.len()],
            &large_frame[..],
            "Reassembled frame must match original"
        );
    }

    #[test]
    fn fec_round_trip_no_loss_reassemble() {
        // Fragment + FEC encode, receive all packets, reassemble without
        // needing recovery.
        let frame_data: Vec<u8> = (0..200u8).collect();

        let mut encoder = FecEncoder::new(0.5);
        let fragmented = fragment_frame_with_fec(
            &frame_data,
            1,
            FRAME_TYPE_P,
            0,
            0,
            Some(&mut encoder),
        );

        // 1 data + 1 parity.
        assert_eq!(fragmented.packets.len(), 2);

        // Feed only the data packet to the reassembler (skip parity).
        let mut reassembler = FrameReassembler::new(16);
        let data_packets: Vec<&VideoPacket> = fragmented
            .packets
            .iter()
            .filter(|p| p.header.frame_type != FRAME_TYPE_PARITY)
            .collect();

        let mut result = None;
        for packet in data_packets {
            result = reassembler.reassemble(packet);
        }
        assert_eq!(result, Some(frame_data));
    }

    #[test]
    fn fec_fragment_frame_with_fec_no_encoder() {
        // When no encoder is provided, should behave like plain fragment_frame.
        let frame_data = b"no fec";
        let fragmented = fragment_frame_with_fec(
            frame_data, 1, FRAME_TYPE_P, 0, 0, None,
        );
        assert_eq!(fragmented.packets.len(), 1);
        assert_eq!(fragmented.packets[0].header.fec_parity_count, 0);
        assert_eq!(fragmented.packets[0].payload, b"no fec");
    }

    #[test]
    fn fec_encoder_encode_empty_packets() {
        let mut encoder = FecEncoder::new(0.5);
        let packets = encoder.encode(vec![]);
        assert!(packets.is_empty());
    }
}
